name: ci

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: self-hosted
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OUTLINE_API_URL: ${{ secrets.OUTLINE_API_URL }}
      OUTLINE_FINGERPRINT: ${{ secrets.OUTLINE_FINGERPRINT }}
      HOST_IP: ${{ secrets.HOST_IP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t registry.lonadels.ru/lonadels/lonadels.ru:latest .
      - name: Push image
        run: |
          docker push registry.lonadels.ru/lonadels/lonadels.ru:latest
  deploy:
    environment: production
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OUTLINE_API_URL: ${{ secrets.OUTLINE_API_URL }}
      OUTLINE_FINGERPRINT: ${{ secrets.OUTLINE_FINGERPRINT }}
      HOST_IP: ${{ secrets.HOST_IP }}
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Pull and restart app
        run: |
          docker compose pull main-app
          docker compose up -d main-app --force-recreate
