name: ci

on:
  push:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-push:
    runs-on: self-hosted
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OUTLINE_API_URL: ${{ secrets.OUTLINE_API_URL }}
      OUTLINE_FINGERPRINT: ${{ secrets.OUTLINE_FINGERPRINT }}
      HOST_IP: ${{ secrets.HOST_IP }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: registry.lonadels.ru
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: |
          docker build `
            --build-arg POSTGRES_USER=${{ env.POSTGRES_USER }} `
            --build-arg POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} `
            --build-arg POSTGRES_DB=${{ env.POSTGRES_DB }} `
            --build-arg DATABASE_URL=${{ env.DATABASE_URL }} `
            --build-arg OUTLINE_API_URL=${{ env.OUTLINE_API_URL }} `
            --build-arg OUTLINE_FINGERPRINT=${{ env.OUTLINE_FINGERPRINT }} `
            --build-arg HOST_IP=${{ env.HOST_IP }} `
            --build-arg DOCKER_USERNAME=${{ env.DOCKER_USERNAME }} `
            --build-arg DOCKER_PASSWORD=${{ env.DOCKER_PASSWORD }} `
            --build-arg API_KEY=${{ env.API_KEY }} `
            -t registry.lonadels.ru/lonadels/lonadels.ru:latest .
      - name: Push image
        run: |
          docker push registry.lonadels.ru/lonadels/lonadels.ru:latest
  deploy:
    environment: production
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OUTLINE_API_URL: ${{ secrets.OUTLINE_API_URL }}
      OUTLINE_FINGERPRINT: ${{ secrets.OUTLINE_FINGERPRINT }}
      HOST_IP: ${{ secrets.HOST_IP }}
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: registry.lonadels.ru
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull and restart app
        run: |
          docker compose pull main-app
          docker compose up -d main-app --force-recreate
